backend:
  name: git-gateway

media_folder: static/assets
public_folder: /assets

collections:
  - name: stories
    label: Stories
    folder: stories
    create: true
    editor:
      preview: false
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    encoding: 'ascii'
    clean_accents: true
    format: 'frontmatter'
    identifier_field: makerName
    fields:
      - { name: date, label: Date, widget: datetime }
      - { name: author, label: Author }
      - {
          name: category,
          label: Category,
          widget: select,
          options:
            [
              'HostNation Blog Post',
              'HostNation Case Study',
              'HostNation Podcast',
              'HostNation Film',
            ],
        }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
