backend:
  name: git-gateway

media_folder: static/assets
public_folder: /assets

collections:
  - name: stories
    label: Stories
    folder: stories
    create: true
    media_folder: 'static/assets/{{title}}'
    public_folder: 'assets/{{title}}'
    path: '{{title}}/index'
    editor:
      preview: false
    fields:
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
