backend:
  name: git-gateway

media_folder: static/assets
public_folder: /assets

collections:
  - name: stories
    label: Stories
    folder: stories
    create: true
    slug: 'index'
    media_folder: ''
    public_folder: ''
    path: '{{title}}/index'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
