backend:
  name: git-gateway

media_folder: static/assets
public_folder: /assets

collections:
  - name: stories
    label: Stories
    folder: stories
    create: true
    editor:
      preview: false
    fields:
      - { name: date, label: Date, widget: datetime }
      - { name: author, label: Author }
      - {
          name: category,
          label: Category,
          widget: select,
          options: ['Blog Post', 'HostNation Case Study'],
        }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
